// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        (unknown)
// source: karma8-discovery/subjects/subject.proto

package subjects

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Type это тип субъекта
type Type int32

const (
	// TypeUnspecified это неизвестный тип субъекта
	Type_TYPE_UNSPECIFIED Type = 0
	// TypeServiceAccount это сервисный аккаунт
	Type_TYPE_SERVICE_ACCOUNT Type = 1
	// TypeUser это пользователь
	Type_TYPE_USER Type = 2
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_SERVICE_ACCOUNT",
		2: "TYPE_USER",
	}
	Type_value = map[string]int32{
		"TYPE_UNSPECIFIED":     0,
		"TYPE_SERVICE_ACCOUNT": 1,
		"TYPE_USER":            2,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_karma8_discovery_subjects_subject_proto_enumTypes[0].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_karma8_discovery_subjects_subject_proto_enumTypes[0]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_karma8_discovery_subjects_subject_proto_rawDescGZIP(), []int{0}
}

// Subject это информация о субъекте
type Subject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// SubjectID это идентификатор субъекта
	SubjectId string `protobuf:"bytes,1,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	// SubjectType это тип субъекта
	SubjectType Type `protobuf:"varint,2,opt,name=subject_type,json=subjectType,proto3,enum=karma8.discovery.subjects.v1.Type" json:"subject_type,omitempty"`
}

func (x *Subject) Reset() {
	*x = Subject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_karma8_discovery_subjects_subject_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Subject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subject) ProtoMessage() {}

func (x *Subject) ProtoReflect() protoreflect.Message {
	mi := &file_karma8_discovery_subjects_subject_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subject.ProtoReflect.Descriptor instead.
func (*Subject) Descriptor() ([]byte, []int) {
	return file_karma8_discovery_subjects_subject_proto_rawDescGZIP(), []int{0}
}

func (x *Subject) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *Subject) GetSubjectType() Type {
	if x != nil {
		return x.SubjectType
	}
	return Type_TYPE_UNSPECIFIED
}

var File_karma8_discovery_subjects_subject_proto protoreflect.FileDescriptor

var file_karma8_discovery_subjects_subject_proto_rawDesc = []byte{
	0x0a, 0x27, 0x6b, 0x61, 0x72, 0x6d, 0x61, 0x38, 0x2d, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65,
	0x72, 0x79, 0x2f, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x2f, 0x73, 0x75, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1c, 0x6b, 0x61, 0x72, 0x6d, 0x61,
	0x38, 0x2e, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x2e, 0x73, 0x75, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x22, 0x6f, 0x0a, 0x07, 0x53, 0x75, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49,
	0x64, 0x12, 0x45, 0x0a, 0x0c, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x22, 0x2e, 0x6b, 0x61, 0x72, 0x6d, 0x61, 0x38,
	0x2e, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x2e, 0x73, 0x75, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0b, 0x73, 0x75, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x2a, 0x45, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x14, 0x0a, 0x10, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49,
	0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x18, 0x0a, 0x14, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x53,
	0x45, 0x52, 0x56, 0x49, 0x43, 0x45, 0x5f, 0x41, 0x43, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x10, 0x01,
	0x12, 0x0d, 0x0a, 0x09, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x53, 0x45, 0x52, 0x10, 0x02, 0x42,
	0x52, 0x5a, 0x50, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x61,
	0x6e, 0x74, 0x79, 0x72, 0x2f, 0x6b, 0x61, 0x72, 0x6d, 0x61, 0x38, 0x2d, 0x68, 0x74, 0x74, 0x70,
	0x2d, 0x66, 0x69, 0x6c, 0x65, 0x2d, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2d, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6b, 0x61, 0x72, 0x6d, 0x61, 0x38,
	0x2d, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x2f, 0x73, 0x75, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_karma8_discovery_subjects_subject_proto_rawDescOnce sync.Once
	file_karma8_discovery_subjects_subject_proto_rawDescData = file_karma8_discovery_subjects_subject_proto_rawDesc
)

func file_karma8_discovery_subjects_subject_proto_rawDescGZIP() []byte {
	file_karma8_discovery_subjects_subject_proto_rawDescOnce.Do(func() {
		file_karma8_discovery_subjects_subject_proto_rawDescData = protoimpl.X.CompressGZIP(file_karma8_discovery_subjects_subject_proto_rawDescData)
	})
	return file_karma8_discovery_subjects_subject_proto_rawDescData
}

var file_karma8_discovery_subjects_subject_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_karma8_discovery_subjects_subject_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_karma8_discovery_subjects_subject_proto_goTypes = []interface{}{
	(Type)(0),       // 0: karma8.discovery.subjects.v1.Type
	(*Subject)(nil), // 1: karma8.discovery.subjects.v1.Subject
}
var file_karma8_discovery_subjects_subject_proto_depIdxs = []int32{
	0, // 0: karma8.discovery.subjects.v1.Subject.subject_type:type_name -> karma8.discovery.subjects.v1.Type
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_karma8_discovery_subjects_subject_proto_init() }
func file_karma8_discovery_subjects_subject_proto_init() {
	if File_karma8_discovery_subjects_subject_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_karma8_discovery_subjects_subject_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Subject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_karma8_discovery_subjects_subject_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_karma8_discovery_subjects_subject_proto_goTypes,
		DependencyIndexes: file_karma8_discovery_subjects_subject_proto_depIdxs,
		EnumInfos:         file_karma8_discovery_subjects_subject_proto_enumTypes,
		MessageInfos:      file_karma8_discovery_subjects_subject_proto_msgTypes,
	}.Build()
	File_karma8_discovery_subjects_subject_proto = out.File
	file_karma8_discovery_subjects_subject_proto_rawDesc = nil
	file_karma8_discovery_subjects_subject_proto_goTypes = nil
	file_karma8_discovery_subjects_subject_proto_depIdxs = nil
}
